"""empty message

Revision ID: 86998500e1a8
Revises: 771692ecfea1
Create Date: 2022-08-31 18:44:32.270244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86998500e1a8'
down_revision = '771692ecfea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_password_hash')
    # ### end Alembic commands ###
